[project]
name = "debugger"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "requests>=2.25.0",
    "python-dotenv>=0.20.0",
    "datasets>=3.6.0",
]
